# alert rules are all stored in this part of the cluster:
# /etc/prometheus/rules/prometheus-monitoring-kube-prometheus-prometheus-rulefiles-0/*.yaml
# running this as a Prometheus Operator means the addition of alert rules will automatically be handled
# running Prometheus stack outside of K8s cluster means we would have to add this in manually and reload Prometheus

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: main-rules
  namespace: monitoring
spec:
  groups:
  - name: main.rules
    rules:
      - alert: HostHighCpuLoad
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 50
        for: 2m
        labels:
          severity: warning
          namespace: monitoring
        annotations:
          description: "Node CPU over 50%\n Value = {{ $value }}\n Instance = {{ $labels.instance }}\n"
          summary: "Host CPU High"