apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-config
  namespace: monitoring
spec:
  route:
    receiver: 'email'
    repeatInterval: 30m
    routes:
    - matchers:
      - name: alertname
        value: HostHighCpuLoad
    - matchers:
      - name: alertname
        value: KubernetesPodCrashLoop
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'robert@stapleton-family.net'
      from: 'robert@stapleton-family.net'
      smarthost: "stapletonfamily-net02c.mail.protection.outlook.com"
      authUsername: 'robert@stapleton-family.net'
      authIdentity: 'robert@stapleton-family.net'
        # access secret in k8s to secure password
      authPassword:
        name: M365-cred
        key: password